### ISSUE TITLE
Quick View content repositions in modal when certain product options are selected

### ISSUE THREAD

**Issue by EdFromBJCS** [bigcommerce/cornerstone#1081]
### Expected behavior

Content in quick view stays within modal when selecting options.

### Actual behavior

Content jumps vertically and clips out of frame when a radio button or option swatch is selected. This seems to only happen on Chrome, and only when there are several options and the option clicked is low down on the list.
![quickview-glitch](https://user-images.githubusercontent.com/17709754/29936032-c3d921f8-8e4e-11e7-830c-67bcba76d544.PNG)

### Steps to reproduce behavior

1. Using Chrome, locate or create a product with several options, including one with radio buttons or swatches. Make sure there are enough options above the radial/swatch that you will have to scroll down to reach it.
2. Click the Quick View button to open the modal
3. Scroll down the options and click a radio or swatch.

**Comment by EdFromBJCS** [comment]
Changing `.modal` from `overflow: hidden;` to `overflow: initial;` seems to fix the problem. Would this change cause any issues?

**Comment by EdFromBJCS** [comment]
@PreciselyAlyss is anyone looking into this?
It seems unlikely to me that overflow would have been set to hidden for no good reason. Should I submit a pull request even if I have serious doubts about my solution?

**Comment by bc-zoharmuzafi** [comment]
@EdFromBJCS Is that still an issue?

**Comment by EdFromBJCS** [comment]
It's fixed in my store, but I tried out vanilla Cornerstone in my sandbox store and it appears to still be an issue.

**Comment by bc-zoharmuzafi** [comment]
@EdFromBJCS Thank you for reporting that issue. We will work on a fix.

**Comment by LordZardeck** [comment]
@bc-zoharmuzafi I can confirm this is still an issue. Thankfully @EdFromBJCS's fix works for us, but I agree, it seems it would have been set to overflow on purpose. The easiest way to reproduce would just activate a mobile view: https://www.screencast.com/t/TY2sdjCUvDX

**Comment by wicelin** [comment]
@bc-zoharmuzafi @EdFromBJCS This is still an issue with cornerstone light theme on Chrome. Adding EdFromBJCS solution stops scroll in the modal and therefore contents can’t be higher than 1 visible page. 
Is someone from BC still looking into this?

**Comment by yurytut1993** [comment]
@bc-zoharmuzafi @EdFromBJCS @LordZardeck @wicelin 
This issue is fixed in [BCTHEME-44](https://jira.bigcommerce.com/browse/BCTHEME-44) and will be added to one of the nearest releases
