### ISSUE TITLE
Nav bar quick search dropdown does not close

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/cornerstone#1198]
### Expected behavior
When you start typing in the nav bar search, you get a dropdown with the results as you type. The X button at top-right corner should close it.

### Actual behavior
However, the only way to close that window is to refresh the page, the X button to close does nothing.

### Steps to reproduce behavior
Just use the quick search.

**Comment by jbruni** [comment]
I'm experiencing this issue, and found I'm not alone: 

https://forum.bigcommerce.com/s/question/0D51B0000432qbRSAQ/i-cant-get-the-nav-bar-quick-search-dropdown-to-close

**Comment by junedkazi** [comment]
@jbruni I just tried the above steps to reproduce the issue & it works for me on the latest cornerstone (1.14.0) with chrome 65.0.3325.181 & safari 11.0.3  on mac OS. Please see the link below as 
https://www.useloom.com/share/6661dd895e044418944609e53e523d51 which has been recorded on chrome. Can you give any additional details on your setup like OS, Browser & version of the browser.

**Comment by jbruni** [comment]
@junedkazi - So... This means it has been fixed in newer version of Cornerstone.
Indeed, the theme I'm working on is based on older version of Cornerstone.
Due to the custom modifications, we currently have no easy path to integrate latest Cornerstone changes...
Anyway, thanks for the information.

**Comment by junedkazi** [comment]
Going to close this one for now. Please reopen if any one is still experiencing similar issue with the latest cornerstone.
