### ISSUE TITLE
Special Characters Not Escaped

### ISSUE THREAD

**Issue by JKarlavige** [bigcommerce/cornerstone#1849]
### Expected behavior
Enter special character such as 58" in product option text field. When clicking "Add to Cart", the cart page and cart preview should show product options with correct characters. However, the preview is showing HTML entities for those characters. The current preview.html file has {{{sanitize value}}} but the characters are still not displaying correctly.

### Actual behavior
The special characters entered in a product option text field are showing HTML entities in the cart page and cart preview.

### Steps to reproduce behavior
On product page which has a text field product option, enter a special character such as 58". The cart preview and cart page shows the HTML entities and not the correct characters.

**Comment by oggede** [comment]
This was an issue that was fixed months ago but has now suddenly reappeared in the last few days. I thinking something in the background has changed and the previous fix no longer works.

**Comment by flair-chris** [comment]
@junedkazi Do you have any idea what is happening here? The characters are also not being escaped when the store owner views the order details. Which makes it really difficult for some of clients that offer customized products to fulfil their orders.

**Comment by oggede** [comment]
What version are you guy's on? I'm on 4.6.1. It may just be effecting a small subset of versions or stores.

**Comment by flair-chris** [comment]
@oggede It is an issue when using Text input as an option. Regardless of theme. So it seems to be how the inputted text is being handled on the back end?

**Comment by oggede** [comment]
Problem now appears to have been fixed. Recommend closing this case.

**Comment by JKarlavige** [comment]
> Problem now appears to have been fixed. Recommend closing this case.

I am still seeing it on the same websites where I first noticed the issue. Is this a BigCommerce issue or Cornerstone specific?

**Comment by bc-as** [comment]
@JKarlavige Are you still running into this issue?  I am not able to replicate it with the current version of Cornerstone.

**Comment by oggede** [comment]
> @JKarlavige Are you still running into this issue? I am not able to replicate it with the current version of Cornerstone.

I am not experiencing this issue anymore. I believe it was a back end problem and not related to the theme. Case close.

**Comment by JKarlavige** [comment]
I am still seeing it on multiple sites, now including the reviews. However, like @oggede said I believe this is a BigCommerce issue and not Cornerstone specific. I will close this out.
